// HypothesisSurface — 3D isometric wireframe rendering of hypothesis
// posteriors across the scenario timeline.
//
// Reference: 3D options implied-volatility surface (@iamai_omni X post,
// generated by GPT-5.5 in Codex). Cyan/teal wireframe mesh on deep-black
// canvas, monospace numeric axis labels, small data dots along ridges,
// isometric perspective with vertical drops to base plane.
//
// Maps to our domain: x = phase 1..6 (scenario time), y = 3 hypothesis
// rows, z = posterior probability. As the scenario plays, the surface
// height shifts — the leading hypothesis rises, alternates fall. Renders
// the make-or-break beat as a topographic ridge that an operator can see
// in one glance instead of reading three rows of text.
//
// Pure SVG, no library dependency. Isometric projection done in-component
// via a simple matrix: world (x, y, z) → screen (sx, sy). Surface mesh
// is a triangulated grid; we render it as line segments (no fill) for the
// pure wireframe look.

import { useMemo } from "react";

import { hypothesesForCase } from "../lib/spineGraph.ts";

interface HypothesisSurfaceProps {
  caseId: string | null;
}

// Posterior trajectory per hypothesis across 6 phases. The shape is a
// reasonable fictional projection of how a Bayesian fusion would evolve
// during the demo replay — matches the workshop spine: hypotheses open
// in P3, posteriors stabilize through P6. v3.3 will drive this from
// real M2 / M7 module output once posterior history is exposed.
function projectedTrajectory(currentPosterior: number, hypothesisIndex: number): number[] {
  // Simple model: starts low (no evidence), rises through P3-P5, settles
  // to the current posterior by P6. Index 0 (primary) rises higher;
  // alternates dampen lower.
  const target = currentPosterior;
  const start = 0.33; // priors before any evidence
  const trajectory: number[] = [];
  for (let phase = 1; phase <= 6; phase++) {
    // S-curve interpolation; alternates have lower amplitude
    const t = (phase - 1) / 5;
    const dampening = hypothesisIndex === 0 ? 1.0 : 0.55;
    const value = start + (target - start) * (t * t * (3 - 2 * t)) * dampening + (hypothesisIndex === 0 ? 0 : start * (1 - t) * 0.4);
    trajectory.push(Math.max(0.02, Math.min(0.95, value)));
  }
  return trajectory;
}

// Isometric projection: world (x, y, z) → screen (sx, sy).
// x along width, y depth into screen, z up.
const ISO_X = { x: 0.866, y: 0 }; // cos(30°)
const ISO_Y = { x: -0.5, y: -0.866 }; // depth into screen, slight up
const ISO_Z = { x: 0, y: -1 }; // pure vertical

function project(x: number, y: number, z: number): [number, number] {
  const sx = x * ISO_X.x + y * ISO_Y.x + z * ISO_Z.x;
  const sy = x * ISO_X.y + y * ISO_Y.y + z * ISO_Z.y;
  return [sx, sy];
}

export function HypothesisSurface({ caseId }: HypothesisSurfaceProps) {
  const data = useMemo(() => {
    if (!caseId) return null;
    const hyps = hypothesesForCase(caseId);
    if (hyps.length === 0) return null;
    return hyps.slice(0, 3).map((node, i) => {
      const dataObj = (node.data ?? {}) as Record<string, unknown>;
      const post = typeof dataObj.posterior === "number" ? (dataObj.posterior as number) : 0.33;
      return {
        id: node.id,
        title: node.title,
        currentPosterior: post,
        trajectory: projectedTrajectory(post, i)
      };
    });
  }, [caseId]);

  if (!data || data.length === 0) {
    return (
      <div className="hyp-surface hyp-surface--empty">
        <span className="empty">no surface for this case</span>
      </div>
    );
  }

  // Geometry: x = phase index (0..5), y = hypothesis index (0..2), z = posterior
  // Scale up to viewport units before isometric projection.
  const X_SCALE = 60; // px per phase step
  const Y_SCALE = 70; // px per hypothesis row (depth)
  const Z_SCALE = 180; // px per posterior unit
  const ROWS = data.length;
  const COLS = 6;

  // Compute projected screen-space points
  type Pt = { x: number; y: number; z: number; sx: number; sy: number; posterior: number; hypIndex: number; phaseIndex: number };
  const points: Pt[][] = [];
  for (let h = 0; h < ROWS; h++) {
    const row: Pt[] = [];
    for (let p = 0; p < COLS; p++) {
      const x = p * X_SCALE;
      const y = h * Y_SCALE;
      const z = data[h].trajectory[p] * Z_SCALE;
      const [sx, sy] = project(x, y, z);
      row.push({ x, y, z, sx, sy, posterior: data[h].trajectory[p], hypIndex: h, phaseIndex: p });
    }
    points.push(row);
  }

  // Compute base-plane points (z=0) for the vertical drop visualization
  const basePts: Array<[number, number]>[] = points.map((row) =>
    row.map((p) => {
      const [sx, sy] = project(p.x, p.y, 0);
      return [sx, sy];
    })
  );

  // Auto-fit viewBox to actual content
  const allSx = points.flatMap((row) => row.map((p) => p.sx))
    .concat(basePts.flatMap((row) => row.map(([sx]) => sx)));
  const allSy = points.flatMap((row) => row.map((p) => p.sy))
    .concat(basePts.flatMap((row) => row.map(([, sy]) => sy)));
  const minSx = Math.min(...allSx) - 60;
  const maxSx = Math.max(...allSx) + 80;
  const minSy = Math.min(...allSy) - 30;
  const maxSy = Math.max(...allSy) + 60;
  const w = maxSx - minSx;
  const h = maxSy - minSy;

  return (
    <div className="hyp-surface">
      <svg
        viewBox={`${minSx} ${minSy} ${w} ${h}`}
        width="100%"
        height="100%"
        preserveAspectRatio="xMidYMid meet"
        style={{ display: "block" }}
      >
        <defs>
          <linearGradient id="hyp-surface-glow" x1="0%" y1="0%" x2="0%" y2="100%">
            <stop offset="0%" stopColor="rgba(78, 215, 215, 0.9)" />
            <stop offset="100%" stopColor="rgba(78, 215, 215, 0.1)" />
          </linearGradient>
        </defs>

        {/* Base plane grid — subtle reference grid at z=0 */}
        <g className="hyp-surface__base">
          {basePts.map((row, h) =>
            row.map(([sx, sy], p) => {
              const next = row[p + 1];
              if (!next) return null;
              return (
                <line
                  key={`base-x-${h}-${p}`}
                  x1={sx}
                  y1={sy}
                  x2={next[0]}
                  y2={next[1]}
                  stroke="rgba(78, 215, 215, 0.18)"
                  strokeWidth="0.6"
                />
              );
            })
          )}
          {Array.from({ length: COLS }).map((_, p) =>
            basePts.slice(0, ROWS - 1).map((row, h) => (
              <line
                key={`base-y-${h}-${p}`}
                x1={row[p][0]}
                y1={row[p][1]}
                x2={basePts[h + 1][p][0]}
                y2={basePts[h + 1][p][1]}
                stroke="rgba(78, 215, 215, 0.18)"
                strokeWidth="0.6"
              />
            ))
          )}
        </g>

        {/* Vertical drops — connect each surface point to its base-plane
            counterpart. Reads as the "height" of each posterior. */}
        <g className="hyp-surface__drops">
          {points.map((row, h) =>
            row.map((pt, p) => {
              const [bsx, bsy] = basePts[h][p];
              return (
                <line
                  key={`drop-${h}-${p}`}
                  x1={pt.sx}
                  y1={pt.sy}
                  x2={bsx}
                  y2={bsy}
                  stroke="rgba(78, 215, 215, 0.25)"
                  strokeWidth="0.5"
                  strokeDasharray="2,2"
                />
              );
            })
          )}
        </g>

        {/* Surface wireframe — connect each point to its right (phase+1)
            and back (hypothesis+1) neighbors. The mesh shape IS the
            posterior surface. */}
        <g className="hyp-surface__mesh">
          {points.map((row, h) =>
            row.map((pt, p) => {
              const segs: JSX.Element[] = [];
              const next = row[p + 1];
              if (next) {
                segs.push(
                  <line
                    key={`mesh-x-${h}-${p}`}
                    x1={pt.sx}
                    y1={pt.sy}
                    x2={next.sx}
                    y2={next.sy}
                    stroke="#5ae0d8"
                    strokeWidth={h === 0 ? 1.6 : 1}
                    opacity={h === 0 ? 0.95 : 0.65}
                  />
                );
              }
              if (h < ROWS - 1) {
                const below = points[h + 1][p];
                segs.push(
                  <line
                    key={`mesh-y-${h}-${p}`}
                    x1={pt.sx}
                    y1={pt.sy}
                    x2={below.sx}
                    y2={below.sy}
                    stroke="#5ae0d8"
                    strokeWidth="0.8"
                    opacity={0.55}
                  />
                );
              }
              return segs;
            })
          )}
        </g>

        {/* Data dots at each grid intersection — small bright cyan circles
            that read like the data points in the IAMAI reference. */}
        <g className="hyp-surface__dots">
          {points.map((row, h) =>
            row.map((pt, p) => (
              <circle
                key={`dot-${h}-${p}`}
                cx={pt.sx}
                cy={pt.sy}
                r={h === 0 ? 2.2 : 1.4}
                fill="#a5f3eb"
                opacity={h === 0 ? 1 : 0.7}
              />
            ))
          )}
        </g>

        {/* Phase axis labels along the bottom (z=0) edge */}
        <g className="hyp-surface__axis-x">
          {basePts[ROWS - 1].map(([sx, sy], p) => (
            <text
              key={`axis-x-${p}`}
              x={sx}
              y={sy + 18}
              textAnchor="middle"
              fontSize="9"
              fontFamily="var(--font-mono)"
              fill="rgba(147, 163, 179, 0.85)"
              letterSpacing="0.08em"
            >
              P{p + 1}
            </text>
          ))}
        </g>

        {/* Hypothesis axis labels along the right edge */}
        <g className="hyp-surface__axis-y">
          {data.map((d, h) => {
            const last = points[h][COLS - 1];
            return (
              <text
                key={`axis-y-${h}`}
                x={last.sx + 14}
                y={last.sy + 4}
                fontSize="9"
                fontFamily="var(--font-mono)"
                fill={h === 0 ? "#5ae0d8" : "rgba(147, 163, 179, 0.7)"}
                letterSpacing="0.04em"
              >
                H{h + 1} · {(d.currentPosterior * 100).toFixed(0)}%
              </text>
            );
          })}
        </g>

        {/* Z-axis label (top-left) */}
        <text
          x={minSx + 8}
          y={minSy + 14}
          fontSize="8"
          fontFamily="var(--font-mono)"
          fill="rgba(93, 110, 128, 0.7)"
          letterSpacing="0.16em"
          style={{ textTransform: "uppercase" }}
        >
          POSTERIOR
        </text>
      </svg>
    </div>
  );
}
